version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  api_project:
    build:
      context: ./OrderProcessingSystem.Api
      dockerfile: Dockerfile
    container_name: api_project_container
    ports:
      - "5001:8080"   
      - "5002:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=OrderProcessingDb;User Id=sa;Password=Sofan@12345#;Trusted_Connection=false;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    networks:
       - my_network
    depends_on:
      - db
      - rabbitmq
      - seq
  consumer_project:
    build:
      context: ./OrderProcessingSystem.OrderPlacedService
      dockerfile: Dockerfile
    container_name: consumer_project_container
    ports:
      - "6001:8080"   
      - "6002:8081"
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    networks:
       - my_network
    depends_on:
      - rabbitmq
      - seq

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_container
    environment:
      SA_PASSWORD: "Sofan@12345#"
      ACCEPT_EULA: "Y"
    networks:
      - my_network
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network
  seq:
     image: datalust/seq:latest
     container_name: seq_container
     ports:
       - "9090:80"
       - "5341:5341"
     environment:
       - ACCEPT_EULA=Y
       - SEQ_FIRSTRUN_ADMINPASSWORD=admin@123
     networks:
       - my_network
     volumes:
       - seq_data:/data
volumes:
    seq_data: